# syntax=docker/dockerfile:1.2

FROM ubuntu
# install git
RUN apt-get update
RUN apt-get install -y git
RUN mkdir /root/.ssh/
RUN touch /root/.ssh/known_hosts
RUN ssh-keyscan github.com >> /root/.ssh/known_hosts
RUN --mount=type=secret,id=id_rsa,target=/root/.ssh/id_rsa git clone git@github.com:Janeeczek/SimpleWeb.git
CMD [ "/bin/bash" ]
